apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gc-first
  labels:
    app: spring-gc-first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gc-first
  template:
    metadata:
      labels:
        app: spring-gc-first
    spec:
      containers:
      - name: spring-gc-first
        image: gcr.io/spring-gc-first/springbootgcp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-gc-first
spec:
  selector:
    app: spring-gc-first
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30018
  type: LoadBalancer
  